services:
  # redis:
  #   image: redis
  #   ports:
  #     - ${REDIS_PORT}:6379
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data